Repository NOAA-RDHPCS/noaa-rdhpcs.github.io, pull requests merged in 2024-07, with the labels that each got.

#110 Add writing guide and expand code style
  CODE_OF_CONDUCT.md
  CODE_STYLE.md
  README.md
  WRITING_GUIDE.md
Labels: documentation

#136 Issue #135 and issue #134 - correct Tectia target link
  source/software/ssh_clients/Tectia/index.rst
Labels: bug

#150 Add ability to add open issue button
  source/_static/css/theme_overrides.css
  source/_static/js/custom.js
  source/_templates/breadcrumbs.html
  source/_templates/footer.html
  source/conf.py
Labels: enhancement

#152 #143 - replace Jet `/lfs1` references with `/lfs5`
  source/contributing/index.rst
  source/data/globus_online_data_transfer.rst
  source/data/summary.rst
  source/data/transferring_data.rst
  source/files/globus_collections.csv
  source/slurm/index.rst
  source/systems/jet_user_guide.rst
Labels: documentation

#154 #153 - MSU updates from Wiki
  source/systems/MSU-HPC_user_guide.rst
Labels: documentation

#86 Start of Google Search
  source/_static/css/theme_overrides.css
  source/_templates/search.html
  source/_templates/searchbox.html
  source/conf.py
Labels: enhancement

#159 Update to remove all build, lint, and linkcheck warnings and errors.
  .github/workflows/publish_docs.yml
  source/accounts/index.rst
  source/accounts/rsa_software_token.rst
  source/conf.py
  source/data/summary.rst
  source/images/cloudprocessing.jpg
  source/images/niagara.jpg
  source/images/winSCP1.png
  source/images/winSCP2.png
Labels: enhancement

#158 Add X2Go document page
  source/images/x2go_newSession.png
  source/images/x2go_password.png
  source/images/x2go_session.png
  source/logging_in/index.rst
  source/software/index.rst
  source/software/x2go.rst
  source/systems/pan/index.rst
Labels: documentation
