Repository NOAA-RDHPCS/noaa-rdhpcs.github.io, pull requests merged in 2024-02, with the labels that each got.

#32 Updated the build/deploy workflow
  .github/workflows/publish_docs.yml
Labels: enhancement

#43 Add build and debug tasks for vscode
  .vscode/launch.json
  .vscode/tasks.json
Labels: enhancement

#50 Fix fix build for windows systems.
  .vscode/tasks.json
Labels: bug

#34 Add lint workflow
  .github/workflows/rst_lint.yml
  Makefile
  requirements.txt
  source/data/gfdl_archive.rst
  source/data/nescc_hpss.rst
  source/data/summary.rst
  source/help/index.rst
  source/help/maintenance.rst
  source/software/python/conda_basics.rst
  source/software/python/index.rst
  source/software/python/jupyter.rst
  source/software/python/miniconda.rst
  source/software/python/parallel_h5py.rst
Labels: enhancement

#51 create policies.rst
  source/queue_policy/policies.rst
Labels: documentation

#52 Globus.xfer.edit
  .gitignore
  .vscode/launch.json
  .vscode/settings.json
  .vscode/tasks.json
  source/queue_policy/index.rst
  source/slurm/index.rst
  source/slurm/shpcrpt.rst
  source/slurm/sreport.rst
Labels: documentation
